### ISSUE TITLE
Posting the delete link into Slack deletes the post

### ISSUE THREAD

**Issue by truh** [skx/markdownshare#5]
Slack and probably some other chat applications crawl the content of posted links. Since just opening the delete link is enough to delete the document, posting the delete link will delete the shared markdown document.

**Comment by skx** [comment]
Yeah sadly I don't think there's too much I can do about that right now.

The intent was always a single-click would remove a post; without confirmation.  But if you share such links that get spidered/fetched then it will obviously happen.  The obvious solution would be to mandate a confirmation, but I don't like that solution so much.

**Comment by truh** [comment]
What do you think about showing a confirmation form on GET and directly deleting the document on POST or DELETE?

An alternative that might work fairly well is to set a cookie when the user visits markdownshare the first time and check the cookie when the delete URL is accessed. When the cookie is not present, show the confirmation box. The assumption under which this solution operates is that the slack fetcher doesn't submit the cookie and that a user who wants to delete a document has visited the page before. The cookie doesn't even have to identify the user.

**Comment by skx** [comment]
I continue to not love the idea, but I'll add a confirmation to make it easier for you.

Do note the recently filed issues #6, and #7 my plan will be to make this service read-only, then gone over the course of the year.   Of course the source is available and it is easy to self-host if you have a spare service.  If it is "private" it is trivial to operate, it is only the public-facing instance which is being a spam magnet.

**Comment by skx** [comment]
https://github.com/skx/markdownshare/releases/tag/release-0.8

**Comment by truh** [comment]
Thanks a lot.
