### ISSUE TITLE
Retire service - make read-only - [1/2]

### ISSUE THREAD

**Issue by skx** [skx/markdownshare#6]
Mark the service as 100% read only on 1st April 2020.

The reason for this is twofold:

* It is an abuse-magnet.
* Supporting the site is an undue burden.

If I were charging for the service it might be worth preserving, but as the site is 99% SPAM I think there is little point in spending the time to add a registration-facility; I'm sure many people would claim to want to pay, but I'm not sure enough would to make it worth-while.

**Comment by skx** [comment]
To give an example of the scale of use:

```
$ markdownshare-linux-amd64 ips | head -n 4
13.81.114.167  25532
131.207.48.128 20093
2.235.189.63   17380
192.99.14.139  16457
```

**Comment by skx** [comment]
* Site is now 100% read-only.
* Will update again shortly to change the banner-text.
  * Otherwise will leave alone until the end of 2020.

**Comment by allyraza** [comment]
Its is sad to see it go have been using it on and off, why not implement some sort spam filtering

**Comment by skx** [comment]
Then it just becomes an arms race, and I sink even **more** time into adopting/adapting to new attacks.

I wish it were a hands-off service, but it no longer is.  I should have made registration mandatory, or charged money, from the start.  But that doesn't fit with the kind of software I like to run.
